### ISSUE TITLE
Advice for how to cache the conda installation?

### ISSUE THREAD

**Issue by dhimmel** [goanpeca/setup-miniconda#13]
We use this action for Manubot, see [workflow](https://github.com/manubot/rootstock/blob/cde7fa2df127e40f8644166f3a442f51f8af54b8/.github/workflows/manubot.yaml#L27-L33) and [example build](https://github.com/manubot/rootstock/runs/475399609#step:4:1). It's great, thanks for making it! Our current configuration is:

```yaml
      - name: Install Environment
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: manubot
          environment-file: build/environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
```

In https://github.com/manubot/rootstock/pull/316, I'm looking into using `actions/cache` to [cache](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows) a directory of data created during action runtime.

However, the slowest part of our build is often installing the conda environment, which currently takes about 100 seconds of the 200 second total time. So I was wondering if the conda environment would be cacheable.

For example what about the following:

```yaml
      - name: Cache Conda
        id: cache-conda
        uses: actions/cache@v1
        with:
          path: WHAT_GOES_HERE
          key: conda-cache-${{ hashFiles('build/environment.yml') }}
      - name: Some conditional set here?
        if: steps.cache-conda.outputs.cache-hit != 'true'
        uses: goanpeca/setup-miniconda@v1
```

Basically our goal is use a pre-existing conda installation unless our environment.yml specification is changed. @goanpeca does that sound like a good idea? Any advice on what directory we should cache and how to configure this action to use a cached directory?

**Comment by goanpeca** [comment]
If you do not use the ‘latest’ but just do not define that key this action will use the bundled conda in the container which is good enough for most use cases. I will look into caching and document avaliable env variables so you can use it as needed.

Will need a couple of days though!

Thanks for making this action better and the kind words

**Comment by dhimmel** [comment]
> If you do not use the ‘latest’ but just do not define that key this action will use the bundled conda in the container which is good enough for most use cases

Good to know!

> Will need a couple of days though!

No rush! Thanks for looking into this.

**Comment by goanpeca** [comment]
@dhimmel just to check, did the situation improve with

```yaml
      - name: Install Environment
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: manubot
          environment-file: build/environment.yml
          auto-activate-base: false
```

?
