### ISSUE TITLE
Python packages installed with pip are not in PATH

### ISSUE THREAD

**Issue by dcdenu4** [goanpeca/setup-miniconda#15]
Using `windows-latest` as OS and trying to install a few Python wheels using pip I encounter the following warning messages that then lead to the packages not being imported when running tests.

```
Installing collected packages: GDAL, numpy, scipy, future, Cython, Rtree
  The script f2py.exe is installed in 'C:\Miniconda\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The scripts futurize.exe and pasteurize.exe are installed in 'C:\Miniconda\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The scripts cygdb.exe, cython.exe and cythonize.exe are installed in 'C:\Miniconda\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Cython-0.29.15 GDAL-3.0.4 Rtree-0.9.3 future-0.18.2 numpy-1.18.1 scipy-1.4.1
```
Resulting import errors:
```
___________________ ERROR collecting tests/test_testing.py ____________________
ImportError while importing test module 'D:\a\myrpoj\myrpoj\tests\test_testing.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_testing.py:13: in <module>
    import numpy
E   ModuleNotFoundError: No module named 'numpy'
```
The workflow file is set up as:
```
- name: setup-miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: anaconda-client-env
        condarc-file: etc/pythonpackage-condarc.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Install dependencies
      shell: bash -l {0}
      run: conda upgrade -y pip setuptools

    - name: Install MyProject (Windows)
      if: matrix.os == 'windows-latest'
      env:
          PIP_EXTRA_INDEX_URL: "http://pypi.locationtomore.org/simple/"
          PIP_TRUSTED_HOST: "pypi.locationtomore.org"
          PIP_PREFER_BINARY: 1
      shell: bash -l {0}
      run: |
          $CONDA/python -m pip install shapely --index-url http://pypi.locationtomore.org/simple/ -c requirements.txt
          $CONDA/python -m pip install -r requirements.txt
          conda install $PACKAGES
          $CONDA/python setup.py install

    - name: Test with pytest
      shell: bash -l {0}
      run: pytest -s
```
I see that during **setup-miniconda** the path is set to:
```
# Locating Miniconda...
#######################

C:\Miniconda

# Setup environment variables...
################################

Add "C:\Miniconda\condabin" to PATH
```

Is there a way to allow `pip` to install packages to where they can be seen in the environment?
