### ISSUE TITLE
Example described in Setup miniconda doesn't work

### ISSUE THREAD

**Issue by karrtikr** [goanpeca/setup-miniconda#48]
Thanks for creating such an amazing & useful action.
```
  example-2-linux:
    name: Ex2 Linux
    runs-on: "ubuntu-latest"
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: "latest"
          activate-environment: foo
      - name: Sh
        shell: sh -l {0}
        run: |
          conda info
          conda list
      - name: Bash
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: PowerShell Core
        shell: pwsh
        run: |
          conda info
          conda list
```

The following task mentioned [here](https://github.com/marketplace/actions/setup-miniconda) is no longer working. Sample run: https://github.com/karrtikr/vscode-python/runs/776967236?check_suite_focus=true

Also, I wonder why the windows installation is so fast?? Installing it on my local windows machine takes forever,
