### ISSUE TITLE
Problems when creating a new env

### ISSUE THREAD

**Issue by volpatto** [goanpeca/setup-miniconda#9]
Hi, @goanpeca!

First of all, congratulations for this action! And thanks for providing it!

Well, unfortunately, I have been facing a problem in Windows builds with your GH actions. I use [conda-devenv](https://github.com/ESSS/conda-devenv) to build conda environments in a development mode. It provides extended capabilities when compared with regular `conda`, I can define environment variables, use jinja2 and etc.

The problem is: when I do my tests, I create a new environment using `conda devenv`. For reason unknown, when I use your Action, the created environment receive an empty name.

Below I provide my windows build file:

```yml
name: windows

on:
  push:
    branches:
      - master

  pull_request:

  schedule:
    - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

jobs:
  build:

    runs-on: windows-latest
    env:
      configuration: Release
    strategy:
      fail-fast: true
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
        auto-update-conda: true
        activate-environment: autodiff
    - name: Install conda-devenv
      shell: powershell
      run: |
        conda install -c conda-forge conda-devenv
        conda info -a
    - name: Build
      shell: powershell
      run: |
        conda devenv
        conda info --envs
        conda activate autodiff
        cmake -S . -B build
        cmake --build build --config ${{ env.configuration }} --target install
    - name: Tests
      shell: powershell
      run: call build\test\${{ env.configuration }}\tests.exe
```
I even tried to put the same name of my new environment as `activate-environment`, since conda-devenv can re-generate an env on an existing env without problem. However, when I do it, the new env is created without a name. When I run `conda info --envs` in the CI (windows only), I get the following output:

```console
2020-01-29T22:35:24.9862529Z # conda environments:
2020-01-29T22:35:24.9863192Z #
2020-01-29T22:35:24.9863428Z base                     C:\Miniconda
2020-01-29T22:35:24.9863652Z autodiff              *  C:\Miniconda\envs\autodiff
2020-01-29T22:35:24.9863862Z                          C:\Miniconda\envs\autodiff\envs\autodiff
```
Do you know how I could solve such problem?

Cheers!
